module HomeHelper

Krieg = ["I'm the conductor of the poop train!", 
	"A meat bicycle for two!", 
	"I'm here to shank and smile!", 
	"It's time to bleed!",
	"Who's ready to flay some scalps?!",
	"BLOOD, BLOOD, BLOOOOD, BLOOD, BLOOOOOOOD!",
	"Mahahaha! My mind is on fire!",
	"(If I harm an innocent person, kill me.)",
	"Over here, my sweet meats, your prince of justice and genocide has something to say: Gone are the days of the tentacle and the age of the gods and mercy is far away... We are the fighters of the middle, the second act in the three-part MEAT play, AND I WILL WIN BEST SUPPORTING ACTOR!",
	"I know what I have become... I am the inside of this world... I taste the gore, and I smell the crying... AND I WANT MORE! I want to bathe in your flesh, I want to savor your fear. I wanna live inside a castle built of your agony, AND I WANT TO CRUMBLE IT WITH AN AXE TO YOUR CAROTID ARTERY!",
	"Keep your chin up, SO I CAN SMASH IT WITH A HAMMER!! Oh, there's no time to cry... We have to squeeze the whimpers out of you like a smothered baby in the night... You won't make a noise now, will you, WILL YOU!! Stay quiet, OR YOU'RE DEAD! NOW AND FOREVER!!",
		"Look at me when I scream at your soul! You loud sacks of filth and sour cream can hit me with your pain pinatas all day, but you'll never take the jellied fantasies of my wasted youth! My stomach is clear and my mind is full of bacon!",
	"I can't see her anymore... She was so clear and bright... but the blood is in my eyes, and now I can only watch the ocean of blood... It's waves crash against my forehead again and again, AND I JUST NEED TO LEARN HOW TO SURF!!",
	"You're gonna scream, just like she did; open mouth, open heart, blood and noise forever piercing my skull, poisoning me with its psychopathic purple liquid. We watched it all, and felt the knife split down the middle... CAN YOU HEAR ME?!",
	"I'll never forget the way her holes cried... The way she screamed in agony as she pushed the knife slowly into my sternum... Such a beautiful symphony of feelings, and at the end of it, she was so much greater! My operatic diva of flesh and steel!!",
	"I'm gonna kill you all, I'm gonna kill your friends and your family, I'm gonna track down your grandparents and turn them inside-out, nobody can stop the blood train that will turn your loved ones into a red splatter across the red tracks of humanity!",
	"Box cover, box cover! I'm the one who eats the stardom! I'm the hero of all the villans! You can't swallow my morality like a lollipop pill! I'll run around your mind and set the world record with my meat sleeves!",
	"This is my favorite song! Dance to the drum beat of the ballistic, fetishistic, sadistic piss-stick! Let the bullets scrape me clean and never ever ever flash a sassy eye at the good doctor!",
	"There is no me, there is no you! There is only the never ending spit and bile of combat! The twenty-four hour murder spree of shining metal! I drink the blood and eat the loot and breathe the numbers, because I AM A MONSTER! NOW AND FOREVER!",
	"(The voices said empty, hollow and thud. The voices said 'empty, hollow and thud'.) THE VOICES SAID 'EMPTY, HOLLOW AND THUD'!!",
	"STOP SCREAMING!",
	"GRIND GRIND GRIND KILL KILL KILL!",
	"(This is gonna get ugly...)",
	"(You asked for it...I can't hold it back any longer...!)",
	"I'M....COMING!!",
	"[maniacal laughter]",
	"I'LL SWALLOW YOUR SOUL!",
	"POUNDS! OF! FLESH!",
	"(It's time...)",
	"NO!! DON'T DO IT!!",
	"I'LL SLICE YOUR EYELIDS SO YOU CAN WATCH THE END!!]",
	"[unintelligible roaring noises]",
	"I told ya what would happen!",
	"I swallowed your soul!",
	"Grind the cartilage!",
	"OPEN YOUR VEINS!",
	"STOP DYING AT ME!!",
	"(Yes, make them pay for what they did to us...)",
	"NEVER STOP THE KILLING!! NEVER!!",
	"Never interupt me!",
	"I feel the hurt...time for a rampage!",
	"Rampage and fill the red bar!",
	"I'm losing blood...gimme yours!",
	"My axe is thirsty!",
	"RAMPAGE TIME!",
	"It's time to go insane!",
	"Rampage and heal, heal and rampage!",
	"From hell's heart, I stab at thee!",
	"Martyr for my little one...",
	"We'll all go together!",
	"I'm taking you with me...",
	"How can I snap your neck if you don't have one?!",
	"Bathe in the meat chunks!",
	"MEAT!!!",
	"It's a baptism of blood!",
	"YOU MAKE ME VOMIT! [laughs]",
	"YOU'RE WRONG!",
	"LOOKED INTO THE HEART OF DARKNESS, AND I ATE IT ALL!!!",
	"Now, GO TO SLEEP!",
	"Now to kill your family! [laughs]",
	"Your FAMILY is next!!",
	"Explosions of life!",
	"Circle of Life!",
	"Born into flame!",
	"Immortal!",
	"DEATH-BIRTH!",
	"I SAW THE LIGHT!!!",
	"LIFE! IS! PAIN!",
	"Wahahahah! I'll take you ALL with me!",
	"Wahahahah! Not fast enough!",
	"We'll all go together!",
	"Your liver is a hood ornament!",
	"Insurance fraud!",
	"Train won't stop!",
	"I love it when you splash on my windshield!",
	"Thank you for riding the Psycho Express, Tooh-tooh! All aboard, I'll be collecting your tickets, we have beverages in the DINING CAR!!!",
	"Stop hitting yourself!!",
	"I hate me!!",
	"CONFUSION!!",
	"The pain goes HERE!",
	"SHUT UP!!",
	"GET OUT OF MY HEAD!!",
	"STOP TALKING TO ME!!",
	"KILL THE LITTLE MAN!!",
	"QUIET!!",
	"GET OUT, GET OUT, GET OUT!!",
	"LET ME LOOSE!!",
	"I CAN'T HEAR YOU!!",
	"NO, NO, NO!!",
	"STOP JUDGING ME!!",
	"YOU CAN'T CONTROL ME!!",
	"(Dude, what are you doing?)",
	"(I deserve this.)",
	"(You can't get rid of me THAT easily...)",
	"Love you...",
	"There's no barbecue 'til I say there's a barbecue!",
	"Can't make the pain scream from down there!",
	"I will murder your death.",
	"You don't die today. YOU DIE EVERY DAY!!",
	"The skargleblargs won't get you today.",
	"You get back on your meat haunches!",
	"Get up, GET UP!! YOU'VE GOT PEOPLE TO HURT!!",
	"Don't worry...it's a good touch.",
	"It's a bad, bad flesh rip that leaves YOU screaming.",
	"(That's right, help 'em. Just like old times...)",
	"Hurt me more!",
	"Hurts so good!",
	"No pain, no gain!",
	"Nothing makes me stronger than a sucking chest wound!",
	"There is nothing but agony!",
	"Stab me a THOUSAND TIMES!!",
	"It hurts, hahahaha! IT HURTS!!",
	"Pain is LIFE!!",
	"Make me bleed!",
	"A pain of many parts!",
	"The sting of POWER!",
	"(Damn, that hurts...)",
	"When revived or being revived",
	"Why aren't you stabbing me?",
	"(Say 'thank you'.) NIPPLE SALADS!! (...Close enough.)",
	"Somebody still cares!?",
	"Stranger Danger!",
	"I can't even feel a knife in my spine...",
	"I was enjoying that!",
	"Stop it! STOP IT! I NEED TO FEEL IT ALL!!",
	"What're you doing to me?!",
	"I am unused to the emotions I am currently feeling!",
	"I'm so happy I could KILL you!",
	"Don't make this weird!",
	"On earning a Second Wind",
	"Immortal!",
	"(Get up...you still got bad guys to kill...)",
	"(On your feet, she might still be out there.)",
	"I'M NEVER SORRY!",
	"NOW YOU SHOULD BE SCARED!",
	"You woke the wrong dog!",
	"I'm not full yet!",
	"Angry, I'm angry!",
	"Let me hear those screams!",
	"My flesh is forever!",
	"Now to SCRAPE YOUR FACE FROM MY FINGERNAILS!",
	"It's strangling time!",
	"I'm back!",
	"Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now...",
	"(Where is she? Is she still alive? Did she get away?)",
	"(If you ever kill an innocent person, I will destroy us.) Shut UP!! (No. That's the deal. You can kill as many of the deserving as you like, but the second your axe touches the flesh of an innocent, I'll end this. All of it. A razor to the veins, just like that fugitive we tried to grab on Hera, remember?) Nnnnngh, get out of my head!! (...I'll take that as a 'yes.')",
	"Somebody open me up and put out the fire in my belly... Put it out with knives and bullets and strangling, or I will eat your nephews!",
	"(Nice change of pace not to be murdering someone for once. Probably temporary, though. I'll lose my mind again and be screaming about meat and fluid soon enough... But this part feels... nice.)",
	"You think this is the end... It will never end. The blood, the screaming, and the teeth, it will start again and again and again, forever!",
	"NIPPLE SALADS! Nipple salads... NIPPLE SALADS!",
	"The silence... Kill it! I'll find you! Quiet noises... and I'll STRANGLE the whispers out of you with a BONESAW!!",
	"(I'm beginning to remember...) Stop it, keep the memories down with a knife in its throat, slash it until it bleeds thought juice across the dirt and it's absorbed into nothingness...",
	"(I can't stop, I can't stop the killing...) AND I DON'T WANT TO!",
	"(Maybe the world is sending me a sign.)",
	"STRONGER!",
	"My pecs have pecs!",
	"I feel a deep, dark warmth...!",
	"I'm rising!",
	"You can't stop me!",
	"No, no, no, no, no!",
	"Who made this gun!?",
	"I ordered a lead salad!",
	"NOTHINGNESS!",
	"[frustrated groan]",
	"(Uh-oh. Math. Hope we don't pop a blood vessel.)",
	"Uhh... the choices are pretzeling my inner lobes!",
	"See the numbers, taste the violence....",
	"But who makes the prettiest noise?",
	"Looking at Skill Trees",
	"Toooo maaaany icons...",
	"My head hurts...",
	"I see red!",
	"Organic arm-jabbers!",
	"Blood drink!",
	"Blasto bandage!",
	"I see feel good needles!",
	"HERE COMES THE BATH-TIME!!",
	"I'm gonna swallow your throat, badass!",
	"I can't wait to taste your lungs!",
	"I'll show you what a badass is!",
	"I see meat muscles!",
	"Don't cry when I pull your lungs out through your chest!",
	"Come to me wrath sponge!",
	"Splash your blood all over me!",
	"Somebody delivered a feast!",
	"I want to hear you scream!",
	"(This one, we can kill.)",
	"When set on fire",
	"I EMBRACE THE FLAME.",
	"HE'S ON FIRE.",
	"(I deserve to burn...)",
	"Keep warm!",
	"(Ow. Ow. Ow ow.)",
	"Hit the one you love! Do it!",
	"I'll eat the pain.",
	"I feel your spanking.",
	"Friendship is pain.",
	"Shoot me 'til you love me!",
	"Friendlyfriendlyfriendly FIRE!!",
	"DON'T...STOP!!",
	"(Oh...they finally turned on me...)",
	"When turning into a Badass Psycho Mutant",
	"I CAN'T TAKE IT!!!",
	"NO! NO, NO, NO!!!",
	"I'VE GOT A HUGE HAND!!!",
	"[angry roar]",
	"(I'm a monster...!) [Said in the tone of his normal outside voice]",
	"(You wanted 'im? You GOT 'IM!)",
	"GOTTA THINK BIG... BIIIIIIG!",
	"(Better this way...)",
	"You don't die, I DIE!",
	"Monster down! Angel up!",
	"(You don't deserve this. I deserve this.)",
	"You're in my spot!",
	"Trading Places!",
	"I like my treasure like I like my baby steaks, raaaaare...",
	"What a shiny soul stabber!",
	"A golden mallet for the meat pounding!",
	"Look at that pungent kill stick.",
	"MINE, MINE, MINE!",
	"A killing tool, put it in me!",
	"(We can use that to kill the deserving, grab it...)",
	"Ooohoohoohoohoo, look at that shiny soul stabber!",
	"I heard a ding!",
	"I'm rising!",
	"All I see is red!",
	"This pleasure is agony!",
	"I'm overflowing!",
	"[short, maniacal laughter]",
	"I want to crush something!",
	"Gun time, fun time!",
	"Do you hear that?!",
	"I AM DEATH!",
	"(Nearly as good as getting paid.)",
	"Looks like them Duke boys are in a peck of trouble!",
	"Somebody catch me!",
	"Fine! I'll make the sky bleed!",
	"FLYING!",
	"I can't breathe!",
	"Bigger mag, better pain!",
	"Stack the frenzy!",
	"Cauterize the wound!",
	"Burning, melting goodness!",
	"Now run, run!",
	"Yes I knew it!",
	"When my powers combine!",
	"Melt for me, pastycakes!",
	"Melt in my mouth!",
	"(This is kinda awful, but mostly awesome...)",
	"I smell a little drop!",
	"BLOOD CONCERTO!!!",
	"Paper cut...",
	"I love it when you bleed at me!",
	"It's a bloody business, Bates!",
	"I lust for your blood!",
	"[Snarling] Hemophilia!",
	"Salt... Good god, where's my salt?!",
	"I feel the crimson!",
	"Blood on the dirt!",
	"The crimson mist is so nutritious!",
	"What a fantastic blood boy I've become!",
	"Friendship is hate!",
	"I'll give you something to cry about!",
	"LOOK AT ME!",
	"You'll never choke ME down!",
	"I am NOT your friend!",
	"(Don't kill this one, they are not deserving.)",
	"That's more like it!",
	"Thank you!",
	"Yeeeeessss, AGAIN!",
	"Thanks for the face pain!",
	"(Don't kill them, this is just for fun, for fun...)",
	"It feels perfect!",
	"I've got to stop.",
	"I didn't mean it!",
	"Feels different this time!",
	"It's the end... But the meat has been prepared!",
	"I slaughtered Steven! He's not even!",
	"I'll strangle you with that tie!",
	"That's wrong! SO WRONG!",
	"But nobody's bleeediiinnng!",
	"I'd rather snort a knife into my brain!",
	"Feels so right!",
	"You're making me giddy!",
	"While there's life, there's meat!",
	"You were fantastic. SO WAS I!",
	"(Teasingly) You should've ruuuun!"]

  def self.quotes(num = 5)
  	quotes_array = []
    num.times { quotes_array.push Krieg.sample }
    quotes_array.join(' ')
  end

  def self.paragraphs(paragraph_count = 3)
    paragraphs = ''
    paragraph_count.times { paragraphs << " #{self.paragraph}</br></br>" } 
    paragraphs.html_safe
  end

  private

  def self.paragraph
    Krieg.shuffle[0..10].join(' ')
  end
end
