module HomeHelper

Krieg = ["I'm the conductor of the poop train!", 
	"A meat bicycle for two!", 
	"I'm here to shank and smile!", 
	"It's time to bleed!",
	"Who's ready to flay some scalps?!",
	"BLOOD, BLOOD, BLOOOOD, BLOOD, BLOOOOOOOD!",
	"Mahahaha! My mind is on fire!",
	"(If I harm an innocent person, kill me.)",
	"Over here, my sweet meats, your prince of justice and genocide has something to say: Gone are the days of the tentacle and the age of the gods and mercy is far away... We are the fighters of the middle, the second act in the three-part MEAT play, AND I WILL WIN BEST SUPPORTING ACTOR!",
	"I know what I have become... I am the inside of this world... I taste the gore, and I smell the crying... AND I WANT MORE! I want to bathe in your flesh, I want to savor your fear. I wanna live inside a castle built of your agony, AND I WANT TO CRUMBLE IT WITH AN AXE TO YOUR CAROTID ARTERY!",
	"Keep your chin up, SO I CAN SMASH IT WITH A HAMMER!! Oh, there's no time to cry... We have to squeeze the whimpers out of you like a smothered baby in the night... You won't make a noise now, will you, WILL YOU!! Stay quiet, OR YOU'RE DEAD! NOW AND FOREVER!!",
		"Look at me when I scream at your soul! You loud sacks of filth and sour cream can hit me with your pain pinatas all day, but you'll never take the jellied fantasies of my wasted youth! My stomach is clear and my mind is full of bacon!",
	"I can't see her anymore... She was so clear and bright... but the blood is in my eyes, and now I can only watch the ocean of blood... It's waves crash against my forehead again and again, AND I JUST NEED TO LEARN HOW TO SURF!!",
	"You're gonna scream, just like she did; open mouth, open heart, blood and noise forever piercing my skull, poisoning me with its psychopathic purple liquid. We watched it all, and felt the knife split down the middle... CAN YOU HEAR ME?!",
	"I'll never forget the way her holes cried... The way she screamed in agony as she pushed the knife slowly into my sternum... Such a beautiful symphony of feelings, and at the end of it, she was so much greater! My operatic diva of flesh and steel!!",
	"I'm gonna kill you all, I'm gonna kill your friends and your family, I'm gonna track down your grandparents and turn them inside-out, nobody can stop the blood train that will turn your loved ones into a red splatter across the red tracks of humanity!",
	"Box cover, box cover! I'm the one who eats the stardom! I'm the hero of all the villains! You can't swallow my morality like a lollipop pill! I'll run around your mind and set the world record with my meat sleeves!",
	"This is my favorite song! Dance to the drum beat of the ballistic, fetishistic, sadistic piss-stick! Let the bullets scrape me clean and never ever ever flash a sassy eye at the good doctor!",
	"There is no me, there is no you! There is only the never ending spit and bile of combat! The twenty-four hour murder spree of shining metal! I drink the blood and eat the loot and breathe the numbers, because I AM A MONSTER! NOW AND FOREVER!",
	"(The voices said empty, hollow and thud. The voices said 'empty, hollow and thud'.) THE VOICES SAID 'EMPTY, HOLLOW AND THUD'!!",
	"STOP SCREAMING!",
	"GRIND GRIND GRIND KILL KILL KILL!",
	"(This is gonna get ugly...)",
	"(You asked for it...I can't hold it back any longer...!)",
	"I'M....COMING!!",
	"[maniacal laughter]",
	"I'LL SWALLOW YOUR SOUL!",
	"POUNDS! OF! FLESH!",
	"(It's time...)",
	"NO!! DON'T DO IT!!",
	"I'LL SLICE YOUR EYELIDS SO YOU CAN WATCH THE END!!]",
	"[unintelligible roaring noises]",
	"I told ya what would happen!",
	"I swallowed your soul!",
	"Grind the cartilage!",
	"OPEN YOUR VEINS!",
	"STOP DYING AT ME!!",
	"(Yes, make them pay for what they did to us...)",
	"NEVER STOP THE KILLING!! NEVER!!",
	"Never interupt me!",
	"I feel the hurt...time for a rampage!",
	"Rampage and fill the red bar!",
	"I'm losing blood...gimme yours!",
	"My axe is thirsty!",
	"RAMPAGE TIME!",
	"It's time to go insane!",
	"Rampage and heal, heal and rampage!",
	"From hell's heart, I stab at thee!",
	"Martyr for my little one...",
	"We'll all go together!",
	"I'm taking you with me...",
	"How can I snap your neck if you don't have one?!",
	"Bathe in the meat chunks!",
	"MEAT!!!",
	"It's a baptism of blood!",
	"YOU MAKE ME VOMIT! [laughs]",
	"YOU'RE WRONG!",
	"LOOKED INTO THE HEART OF DARKNESS, AND I ATE IT ALL!!!",
	"Now, GO TO SLEEP!",
	"Now to kill your family! [laughs]",
	"Your FAMILY is next!!",
	"Explosions of life!",
	"Circle of Life!",
	"Born into flame!",
	"Immortal!",
	"DEATH-BIRTH!",
	"I SAW THE LIGHT!!!",
	"LIFE! IS! PAIN!",
	"Wahahahah! I'll take you ALL with me!",
	"Wahahahah! Not fast enough!",
	"We'll all go together!",
	"Your liver is a hood ornament!",
	"Insurance fraud!",
	"Train won't stop!",
	"I love it when you splash on my windshield!",
	"Thank you for riding the Psycho Express, Tooh-tooh! All aboard, I'll be collecting your tickets, we have beverages in the DINING CAR!!!",
	"Stop hitting yourself!!",
	"I hate me!!",
	"CONFUSION!!",
	"The pain goes HERE!",
	"SHUT UP!!",
	"GET OUT OF MY HEAD!!",
	"STOP TALKING TO ME!!",
	"KILL THE LITTLE MAN!!",
	"QUIET!!",
	"GET OUT, GET OUT, GET OUT!!",
	"LET ME LOOSE!!",
	"I CAN'T HEAR YOU!!",
	"NO, NO, NO!!",
	"STOP JUDGING ME!!",
	"YOU CAN'T CONTROL ME!!",
	"(Dude, what are you doing?)",
	"(I deserve this.)",
	"(You can't get rid of me THAT easily...)",
	"Love you...",
	"There's no barbecue 'til I say there's a barbecue!",
	"Can't make the pain scream from down there!",
	"I will murder your death.",
	"You don't die today. YOU DIE EVERY DAY!!",
	"The skargleblargs won't get you today.",
	"You get back on your meat haunches!",
	"Get up, GET UP!! YOU'VE GOT PEOPLE TO HURT!!",
	"Don't worry...it's a good touch.",
	"It's a bad, bad flesh rip that leaves YOU screaming.",
	"(That's right, help 'em. Just like old times...)",
	"Hurt me more!",
	"Hurts so good!",
	"No pain, no gain!",
	"Nothing makes me stronger than a sucking chest wound!",
	"There is nothing but agony!",
	"Stab me a THOUSAND TIMES!!",
	"It hurts, hahahaha! IT HURTS!!",
	"Pain is LIFE!!",
	"Make me bleed!",
	"A pain of many parts!",
	"The sting of POWER!",
	"(Damn, that hurts...)",
	"When revived or being revived",
	"Why aren't you stabbing me?",
	"(Say 'thank you'.) NIPPLE SALADS!! (...Close enough.)",
	"Somebody still cares!?",
	"Stranger Danger!",
	"I can't even feel a knife in my spine...",
	"I was enjoying that!",
	"Stop it! STOP IT! I NEED TO FEEL IT ALL!!",
	"What're you doing to me?!",
	"I am unused to the emotions I am currently feeling!",
	"I'm so happy I could KILL you!",
	"Don't make this weird!",
	"Immortal!",
	"(Get up...you still got bad guys to kill...)",
	"(On your feet, she might still be out there.)",
	"I'M NEVER SORRY!",
	"NOW YOU SHOULD BE SCARED!",
	"You woke the wrong dog!",
	"I'm not full yet!",
	"Angry, I'm angry!",
	"Let me hear those screams!",
	"My flesh is forever!",
	"Now to SCRAPE YOUR FACE FROM MY FINGERNAILS!",
	"It's strangling time!",
	"I'm back!",
	"Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now... Why aren't my fingers in someone's eye sockets right now...",
	"(Where is she? Is she still alive? Did she get away?)",
	"(If you ever kill an innocent person, I will destroy us.) Shut UP!! (No. That's the deal. You can kill as many of the deserving as you like, but the second your axe touches the flesh of an innocent, I'll end this. All of it. A razor to the veins, just like that fugitive we tried to grab on Hera, remember?) Nnnnngh, get out of my head!! (...I'll take that as a 'yes.')",
	"Somebody open me up and put out the fire in my belly... Put it out with knives and bullets and strangling, or I will eat your nephews!",
	"(Nice change of pace not to be murdering someone for once. Probably temporary, though. I'll lose my mind again and be screaming about meat and fluid soon enough... But this part feels... nice.)",
	"You think this is the end... It will never end. The blood, the screaming, and the teeth, it will start again and again and again, forever!",
	"NIPPLE SALADS! Nipple salads... NIPPLE SALADS!",
	"The silence... Kill it! I'll find you! Quiet noises... and I'll STRANGLE the whispers out of you with a BONESAW!!",
	"(I'm beginning to remember...) Stop it, keep the memories down with a knife in its throat, slash it until it bleeds thought juice across the dirt and it's absorbed into nothingness...",
	"(I can't stop, I can't stop the killing...) AND I DON'T WANT TO!",
	"(Maybe the world is sending me a sign.)",
	"STRONGER!",
	"My pecs have pecs!",
	"I feel a deep, dark warmth...!",
	"I'm rising!",
	"You can't stop me!",
	"No, no, no, no, no!",
	"Who made this gun!?",
	"I ordered a lead salad!",
	"NOTHINGNESS!",
	"[frustrated groan]",
	"(Uh-oh. Math. Hope we don't pop a blood vessel.)",
	"Uhh... the choices are pretzeling my inner lobes!",
	"See the numbers, taste the violence....",
	"But who makes the prettiest noise?",
	"Looking at Skill Trees",
	"Toooo maaaany icons...",
	"My head hurts...",
	"I see red!",
	"Organic arm-jabbers!",
	"Blood drink!",
	"Blasto bandage!",
	"I see feel good needles!",
	"HERE COMES THE BATH-TIME!!",
	"I'm gonna swallow your throat, badass!",
	"I can't wait to taste your lungs!",
	"I'll show you what a badass is!",
	"I see meat muscles!",
	"Don't cry when I pull your lungs out through your chest!",
	"Come to me wrath sponge!",
	"Splash your blood all over me!",
	"Somebody delivered a feast!",
	"I want to hear you scream!",
	"(This one, we can kill.)",
	"When set on fire",
	"I EMBRACE THE FLAME.",
	"HE'S ON FIRE.",
	"(I deserve to burn...)",
	"Keep warm!",
	"(Ow. Ow. Ow ow.)",
	"Hit the one you love! Do it!",
	"I'll eat the pain.",
	"I feel your spanking.",
	"Friendship is pain.",
	"Shoot me 'til you love me!",
	"Friendlyfriendlyfriendly FIRE!!",
	"DON'T...STOP!!",
	"(Oh...they finally turned on me...)",
	"When turning into a Badass Psycho Mutant",
	"I CAN'T TAKE IT!!!",
	"NO! NO, NO, NO!!!",
	"I'VE GOT A HUGE HAND!!!",
	"[angry roar]",
	"(I'm a monster...!) [Said in the tone of his normal outside voice]",
	"(You wanted 'im? You GOT 'IM!)",
	"GOTTA THINK BIG... BIIIIIIG!",
	"(Better this way...)",
	"You don't die, I DIE!",
	"Monster down! Angel up!",
	"(You don't deserve this. I deserve this.)",
	"You're in my spot!",
	"Trading Places!",
	"I like my treasure like I like my baby steaks, raaaaare...",
	"What a shiny soul stabber!",
	"A golden mallet for the meat pounding!",
	"Look at that pungent kill stick.",
	"MINE, MINE, MINE!",
	"A killing tool, put it in me!",
	"(We can use that to kill the deserving, grab it...)",
	"Ooohoohoohoohoo, look at that shiny soul stabber!",
	"I heard a ding!",
	"I'm rising!",
	"All I see is red!",
	"This pleasure is agony!",
	"I'm overflowing!",
	"[short, maniacal laughter]",
	"I want to crush something!",
	"Gun time, fun time!",
	"Do you hear that?!",
	"I AM DEATH!",
	"(Nearly as good as getting paid.)",
	"Looks like them Duke boys are in a peck of trouble!",
	"Somebody catch me!",
	"Fine! I'll make the sky bleed!",
	"FLYING!",
	"I can't breathe!",
	"Bigger mag, better pain!",
	"Stack the frenzy!",
	"Cauterize the wound!",
	"Burning, melting goodness!",
	"Now run, run!",
	"Yes I knew it!",
	"When my powers combine!",
	"Melt for me, pastycakes!",
	"Melt in my mouth!",
	"(This is kinda awful, but mostly awesome...)",
	"I smell a little drop!",
	"BLOOD CONCERTO!!!",
	"Paper cut...",
	"I love it when you bleed at me!",
	"It's a bloody business, Bates!",
	"I lust for your blood!",
	"[Snarling] Hemophilia!",
	"Salt... Good god, where's my salt?!",
	"I feel the crimson!",
	"Blood on the dirt!",
	"The crimson mist is so nutritious!",
	"What a fantastic blood boy I've become!",
	"Friendship is hate!",
	"I'll give you something to cry about!",
	"LOOK AT ME!",
	"You'll never choke ME down!",
	"I am NOT your friend!",
	"(Don't kill this one, they are not deserving.)",
	"That's more like it!",
	"Thank you!",
	"Yeeeeessss, AGAIN!",
	"Thanks for the face pain!",
	"(Don't kill them, this is just for fun, for fun...)",
	"It feels perfect!",
	"I've got to stop.",
	"I didn't mean it!",
	"Feels different this time!",
	"It's the end... But the meat has been prepared!",
	"I slaughtered Steven! He's not even!",
	"I'll strangle you with that tie!",
	"That's wrong! SO WRONG!",
	"But nobody's bleeediiinnng!",
	"I'd rather snort a knife into my brain!",
	"Feels so right!",
	"You're making me giddy!",
	"While there's life, there's meat!",
	"You were fantastic. SO WAS I!",
	"(Teasingly) You should've ruuuun!"]

Zero = ["Whoops!",
	"If only I had five fingers...",
	"Darn!",
	"Dropped it.",
	"Slipped!",
	"Joining a game",
	"Where is the target?",
	"Just tell me what to shoot.",
	"What's the hold up? / Is someone in the bathroom? / Are you on the phone?",
	"What is going on? / Why have my limbs stopped moving? / Has my heart stopped?",
	"Bor-ed, bor-ed, bored / Bored, bored, bored, bored, bored, bored, bored / I am really bored.",
	"Boredom is my lot, / As I lack autonomy / To move my own feet.",
	"An idle mind is / A very dangerous thing / I think of violence.",
	"I am bored as hell / I would like to kill something / Can we friggin go?",
	"I sit here and wait / So eager to move onward / But it's all in vain.",
	"Can we start moving? / I grow tired of this spot / I long to explore.",
	"The peaceful silence / Penetrates my whole being / It's so very dull.",
	"Attempting to travel while other players are busy",
	"Someone is busy. / Now we play the waiting game; / Everyone loses.",
	"What is the holdup? / Is someone in the bathroom? / Are you on the phone?",
	"Your eyes deceive you / An illusion fools you all / I move for the kill.",
	"How hilarious / You just set off my trap card / Your death approaches.",
	"The true world revealed / Weaknesses now known to me / Time to go to work.",
	"And I disappear / A ghost amidst the combat / Preparing to strike.",
	"I vanish.",
	"Stealth!",
	"Good bye!",
	"Ghosting.",
	"A critical hit / So very satisfying / I live for such kills.",
	"Critical killing / Is an art unto itself / And I am Rembrandt.",
	"A critical kill / Showers me in blood and spit / How enjoyable.",
	"That was your own fault / You should have paid attention / And looked through the lie.",
	"Sorry, did that hurt? / That 'sorry' was sarcasm / I am not sorry.",
	"I enjoy that.",
	"Heehee.",
	"Ow.",
	"Ouch.",
	"Sucker.",
	"Precision!",
	"Grenade out!",
	"Here! Grenade!",
	"'Nade!",
	"I feel the burning / Eating through my equipment / Must stop, drop, and roll.",
	"I'm covered in slag! / I must seek cover quickly / or pain is coming.",
	"Disgusting, this slag / Inelegant chemical / Increases damage.",
	"Slagged!",
	"My armor!",
	"A new instrument, / Waiting for a sonata / That I will conduct.",
	"Maybe I'll use you / To blow a midget's head off. / Or maybe I won't.",
	"Mine.",
	"Nice.",
	"Impressive.",
	"Well, well...",
	"Not bad.",
	"Comparisons made / But which is superior? / A tough decision.",
	"Hmmm...",
	"Get back on your feet / I will help you up, and then / We will kill more stuff!",
	"Keep shooting!",
	"Keep calm.",
	"Do not panic.",
	"I have you.",
	"Killing an enemy",
	"A most confused death / Dead before he even knew / Where I had struck from.",
	"Striking from nowhere / Killing with accuracy / This is who I am.",
	"Yoo-hoo, stupid guy / I was really over here / Too bad you're dead now.",
	"I am everywhere / And yet, I am nowhere, too / I am infinite.",
	"Farewell, foolish thing / Know that you have been deceived / As your soul moves on.",
	"This is how you die / A spectacle of violence / Gorgeous and ugly.",
	"I relish your death / You are so unsuspecting / How satisfying.",
	"I say, boom biatch / That's what you get for messing / With the Assassin.",
	"I have destroyed you / A deadly shot from nowhere / The ghost Assassin.",
	"Over here you fools / That was but an illusion / I am your true foe.",
	"You fought well creature / But I fought so much better / I'll pick your corpse now.",
	"Assassinated / What a satisfying word / With five syllables.",
	"What happened to you? / So strong, imposing, fearsome / Oh yeah, I killed you.",
	"I witness your death / You were so unsuspecting / How satisfying.",
	"Assassins never die!",
	"Bow to my weaponary!",
	"Unworthy opponents.",
	"Fear my skills!",
	"Easy.",
	"Warning, badass!",
	"Badass approaching!",
	"Greetings, badass.",
	"Hello, badass.",
	"Badass sighted.",
	"Attention! Badass.",
	"Badass incoming!",
	"Incoming badass!",
	"Hark! Badass.",
	"That is called 'roadkill' / Not the cleverest of words / But appropriate.",
	"This is the story / All about how my life got / Flipped, turned upside-down.",
	"What was that speed bump / That fell under my tires? / Was that thing alive?",
	"Idiots.",
	"Bump!",
	"Funny.",
	"System crashed.",
	"Getting crippled",
	"I am nearly dead / It's time for a second wind / Let my aim be true.",
	"I will not die here / I still have too much to do / And too much ammo.",
	"Dammit!",
	"Come on!",
	"I won't die today / Not while I still have ammo / I am a badass.",
	"I have arisen / You will regret harming me / My vengeance at hand.",
	"Second Wind achieved / Pulled back from the brink of death / I'm ready for more.",
	"I'm back from the dead / To continue to raise hell / Get out of my way.",
	"You should now be scared / I don't die so easily / And now I am pissed.",
	"Nice try savages / I am not the dying type / You shall die instead.",
	"This does not end here / I have much further to go / Before I fall dead.",
	"I got Second Wind / Metaphorically speaking / Breath overrated.",
	"I am eternal / Death will never capture me / My skills exceed his.",
	"I do not think so.",
	"Your mistake.",
	"Yes!",
	"I'm ready.",
	"Fool.",
	"What is next?",
	"I'm empty.",
	"Well, crap.",
	"Curses, empty.",
	"No ammo.",
	"That's unfortunate.",
	"Ammo dry.",
	"Ammunition required.",
	"Ammo depleted.",
	"Munitions dry.",
	"Ammo necessary.",
	"I thank you for your / Kindness and sincerity. / Now, let's kill some stuff.",
	"Thank you for saving / A not so innocent life / By reviving me.",
	"Levelled up.",
	"That felt good.",
	"Why, yes. I do have the skills to pay all my bills... figuratively.",
	"Oh, what? Yeah, what, bitch? / Yeah, I just slapped you and stuff. / What you gonna do?",
	"Let's duel, you and I / So we can compare weapons / And know who is more skilled.",
	"Let us fight.",
	"Duel. Now!",
	"I challenge you.",
	"A chance to spar / Is something I adore / I'm ready to fight.",
	"Was that a stiff wind? / Or a fly landing on me? / I barely felt it.",
	"You sure?",
	"Your mistake.",
	"Death wish, huh?",
	"A victory earned / A hard fought battle, that was / I honor my foe.",
	"That was a fine fight / I say that due to your skill / Not because I won.",
	"Easy.",
	"I win.",
	"Victorious.",
	"Back on your feet.",
	"I lost fair and square / Whatever that dumb phrase means / Who loses a square?.",
	"Well done.",
	"Rematch. Now!",
	"Surprising.",
	"Tying in a duel",
	"The battle complete / The warriors are equal / Identical skills.",
	"A tie? Disappointing.",
	"Unexpected.",
	"As my voice changes / I cannot help but feel wrong / I sound like a jerk.",
	"Now, I have Jack's voice / I truly understand him / He is an asshole.",
	"Since I speak as Jack / I know him, inside and out / Which sounds kind of gross.",
	"I miss my old voice / I sound like a jackass now / Pun not intended.",
	"I found equipment.",
	"Beautiful weaponry!",
	"Poetic armaments.",
	"I feel the Wind.",
	"I'm ready!",
	"No! Serenity!",
	"Good!",
	"Fool!",
	"Peek-a-boo!",
	"Gotcha!",
	"Over here!",
	"I disappear!",
	"Goodbye!",
	"Your mistake.",
	"I don't think so.",
	"Wrong move!"]

Gaige = ["I say MECHRO, you say MANCER. MECHRO! (no reply) ...You guys suck!",
	"It's cool everybody. I'm here...",
	"Anybody have some mechros they need manced?",
	"Am I a hero... or something?",
	"Live! LIVE!",
	"Argh... How much do you weigh?",
	"Cover me brah!",
	"Worry not citizen, I'll save you.",
	"Come on, noob! Nah, I'm just playin', you're cool...",
	"Wow! You work out?",
	"Critical Kill",
	"Noob!",
	"GG.",
	"Fun!",
	"Nearly!",
	"Squish!",
	"Boop!",
	"Crit-i-cal kill!",
	"LAWL",
	"Doink!",
	"Kablam!",
	"Hehe, Just how I do?",
	"SATISFACTION!",
	"Ugh, I've got some brain on my shoes. *Sniff* I like it.",
	"Man!",
	"Oh!",
	"Don't screw with a girl and her robot!",
	"Nice one, boy!",
	"You're bringing a tear to my eye...",
	"Robot: One! Uglies: Zerooo!",
	"Best robot ever.",
	"Oooh. Right in the wingnut.",
	"Ha ha!",
	"Ha! Ha! Ha! Ha! Ha! Ha! Ha! Ha!",
	"Love ya, bot.",
	"Respect the robot!",
	"I need to build you an extra arm JUST for high-fives!",
	"Hell yes! I can't believe you only got third place in the science fair.",
	"I am the strongest girl alive!",
	"I am the greatest engineer alive!",
	"You are a mean machine!",
	"Terminated!",
	"Good one, babe!",
	"Eh, accuracy's overrated anyway.",
	"I'm feeling awesomer.",
	"This could be the beginning of something awesome.",
	"Not a bad start.",
	"Start the Anarchy!",
	"Start the stacking!",
	"This is getting good.",
	"Wonder how many stacks I can get.",
	"Alright, lets keep this going.",
	"(mumbling) It's a start...",
	"Alright, more Anarchy!",
	"Anarchy forever!",
	"Lets keep it up.",
	"If I hit ya, you're going to feel it.",
	"(Giggles)",
	"I'm feeling it!",
	"Not bad, not bad.",
	"I'll have some more Anarchy, thank you!",
	"Anarchy up!",
	"More stacks!",
	"Anarchy, baby!",
	"This is getting awesome!",
	"Come at me jokers!",
	"Anarchy on Pandora!",
	"(laughs) Everything's going to die!",
	"So inaccurate but so awesome!",
	"More Anarchy, more!",
	"Don't accidentally reload, don't accidentally reload!",
	"I'm getting phat stacks.",
	"Stack 'em up, stack 'em up!",
	"This is getting ridiculous!",
	"My hit to miss ratio is sadness!",
	"Smash the system!",
	"Anarchy!",
	"I am the strongest girl alive!",
	"You can't stop me!",
	"More power!",
	"Don't stop now!",
	"Gimme more Anarchy!",
	"Stack 'em and bag 'em!",
	"I'm getting a god complex and I LIKE IT!",
	"Punk never dies!",
	"Meedly-meedly-mowwww...I know, Im so bad at this.",
	"Accuracy can suck it!",
	"Never-ending stacks!",
	"(Evil laugh)",
	"When I hit you, IT WILL HURT!",
	"So many stacks!",
	"The power!",
	"I think my reload buttons broken!",
	"UNLIMITED POWER!",
	"I am the bringer of death!",
	"BLOOD!",
	"I'm going mildly insane!",
	"God damn, I am so hardcore!",
	"YEAAAAAH!",
	"I feel the cosmos!",
	"POWER!",
	"I WILL NEVER HIT ANYTHING!",
	"RIDONCULOUS!",
	"I am everything!",
	"I probably won't hit anything but whatever!",
	"Start running, clowns!",
	"Mechromancer angry!",
	"I will destroy everything!",
	"I deal DEATH!",
	"ROCK ON!",
	"Why am I still doing this?!",
	"It's getting really hard to hit stuff!",
	"If I go down, I'm screwed!",
	"I am stupid powerful!",
	"I AM THE ALPHA AND THE OMEGA!",
	"Meedly-meedly-meedly-mowwww... Nope, still bad! That was worse, I think.",
	"Teehee.",
	"Yes! YESSS!",
	"SO MUCH STACKS!",
	"The stacks... THE STACKS!",
	"Sure! Why not!",
	"EVIL MANIACAL LAUGHTER!",
	"Lets get it on!",
	"I AM THE INFINITE!",
	"BOOYAH!",
	"I GOT THE TEAM ON MY BACK!",
	"This is actually stupid now!",
	"I will miss almost every shot, and I don't care!",
	"I regret nothing!",
	"YEAH BOY!",
	"ALLEN WRITE SOME DIALOGUE HERE!",
	"PLAYER? WHAT! ARE! YOU! DOING?!",
	"How is this possible?!",
	"Too many stacks!",
	"I have like negative accuracy right now!",
	"You're breaking the game, dude!",
	"God help you all if I actually HIT something!",
	"I AM THE GOD OF DAMAGE!",
	"I don't even remember what accuracy MEANS!",
	"ANARCHY FOREVERRRR!!! AND EVERRRR!!!",
	"NooooooooooOOOOOOOoooooooooooOOOOoooooo.",
	"Ugh... What was I thinking?!",
	"Wait -- Did I just?! -- Ugh... Dang it!",
	"Son of a whore!",
	"Oh, now I can actually hit stuff again.",
	"Back to zero.",
	"Let's start at the very beginning.",
	"Reset!",
	"Time for a hard reset!",
	"Accuracy, how I've missed you!",
	"Normalizing!",
	"I feel normal again.",
	"AAAAAND normal.",
	"Starting over.",
	"Aw crap!",
	"My anarchy!",
	"I lost my anarchy! This is like the worst day ever!",
	"Where'd my anarchy go?",
	"Not my anarchy!",
	"I miss you already anarchy.",
	"Come on! I can take ya!",
	"This is nothing! I've done worse to myself!",
	"I am gonna smack the bitch outta you!",
	"Hax!",
	"I can fix this!",
	"Okay now I'm mad!",
	"Come closer jerkwads! I've got something to show ya'!",
	"Okay playtime's over.",
	"You're not gonna like what happens now.",
	"Open wide, jackholes!",
	"Don't mess with me!",
	"NBD.",
	"I LIVE!",
	"What'd I tell you, suckers?",
	"Up and running!",
	"Now you're gonna get it!",
	"You ain't gankin' me that easy.",
	"High-larious.",
	"Heyoo.",
	"Kaboosh!",
	"Hehe...",
	"Oh, I love you, car!",
 	"Haha! Yes!",
	"Boosh!",
	"Oh, I love you, car!",
	"EXPLOSIONS!",
	"Ohooohoho maaaan.",
	"Yahoo!",
	"General combat",
	"Multi-Kill kill kill!",
	"M-M-M-Monster Kill kill kill!",
	"Dominating.",
	"Unstoppable!",
	"Oh, that was close. No it wasn't!",
	"Found a badass!",
	"That's right, fear the cute little girl!",
	"Level up!",
	"Ready for an upgrade, bot?",
	"So much hotness.",
	"Deathtrap wants an upgrade? Deathtrap gets an upgrade!",
	"I want that. And that. And that.",
	"What do I want to kick ass at next?",
	"That Anarchy one looks tricky...",
	"Ohh, I just want you all!",
	"Ohh, I'm likin' my options.",
	"Oh, I love comparin' loot!",
	"Numbers, numbers, math math math.",
	"Oh, I wanna use 'em both!",
	"Show me some green arrows.",
	"Not bad!",
	"Shh. Don't worry baby. I'll take good care of you.",
	"What's your name, sexy?",
	"I want it!",
	"Why, hello there.",
	"Rock and roll.",
	"Hooray!",
	"Yeah. I'm pretty good.",
	"MVP.",
	"The completionist in me is like YEEAAAH!",
	"Your face is stupid.",
	"Me and robot are gonna bitch smack ya!",
	"Let's dance!",
	"Come on! It'll be fun!",
	"Snik snik, bitches!",
	"Third place. Third place! I built a robot that can turn human beings into jelly with the push of a button and that what's-his-face gives me THIRD PLACE! in the planet-wide science fair. At least around here people appreciate my talents.",
	"If I don't shoot, repair, or screw something in the next few minutes, we're gonna have a problem.",
	"FML",
	"Urgh, this is dull!",
	"I wanna go do stuff!",
	"(Beatboxing Sounds) Bored Bored Bored.",
	"Laaaaag",
	"Oh God! It smells like piss and nachos!",
	"It's in my mouth, umm you guys, it's in my mouth!",
	"Testing? Testing one two? One two. And now I have the voice of a douchebag. Great.",
	"I need to build you an extra arm just for high-fives!",
	"Haha, now you're gonna get it!",
	"Man, this whole 'Speaking with the voice of an older man' thing is nowhere near as hot as I thought it would be.",
	"Beatbox time! (Beatboxing sounds) I'm the Mechromancer and I'm here to say-Aw, screw it, it's just not the same! Freakin' Jack voice!",
	"You know, maybe this voice ain't so bad. Hello, ladies- Oh god, creepycreepycreepy! Never doing that again!",
	"This is some impressive workmanship!",
	"Shiny stuff!",
	"Nothing sexier than a chest full of loot!",
	"BITCHES!",
	"Up and RUNNING!",
	"Robot: one, Uglies: zero!",
	"Super robot violence fun time!",
	"Number five alive!",
	"I'm gonna slap the BITCH outta you!",
	"Hax!",
	"Anybody needs some healin'?",
	"Med-Hypos.",
	"Is that healin' stuff?",
	"Health!",
	"(Singing Lullaby) Waitin' on you.",
	"Just waitin'.",
	"Still working on something, huh?",
	"Crankshaft! I'm empty!",
	"Nuts! No more bullets!",
	"Screw it! I don't need ammo!",
	"Son of a whore!",
	"Where'd all the bullets go?",
	"Hey! Could you give me some of those bullets back?",
	"I'm out!",
	"No more ammo!",
	"High and dry!",
	"I miss my ammo.",
	"This will bring the hurt!",
	"Discord, Ehh! Not yet!",
	"When to discord? When to discord?",
	"More hurt for the discord!",
	"My discord will cause serious pain!",
	"Just wait until I reload.",
	"Cant wait to discooord.",
	"Gotta keep buffin that discord!",
	"Chargin up for that discord.",
	"Gotta pick the right time to discord"]

  def self.quotes(num = 5)
  	quotes_array = []
    num.times { quotes_array.push Krieg.sample }
    quotes_array.join(' ')
  end

  def self.kriegparagraphs(paragraph_count = 3)
    kriegparagraphs = ''
    paragraph_count.times { kriegparagraphs << " #{self.kriegparagraph}</br></br>" } 
    kriegparagraphs.html_safe
  end

  def self.zeroparagraphs(paragraph_count = 3)
    zeroparagraphs = ''
    paragraph_count.times { zeroparagraphs << " #{self.zeroparagraph}</br></br>" } 
    zeroparagraphs.html_safe
  end

  def self.gaigeparagraphs(paragraph_count = 3)
    gaigeparagraphs = ''
    paragraph_count.times { gaigeparagraphs << " #{self.gaigeparagraph}</br></br>" } 
    gaigeparagraphs.html_safe
  end


  private

  def self.kriegparagraph
    Krieg.shuffle[0..14].join(' ')
  end

  def self.zeroparagraph
    Zero.shuffle[0..20].join(' ')
  end

  def self.gaigeparagraph
    Gaige.shuffle[0..20].join(' ')
  end
end
